import { JobListing } from "../features/jobs/types";


export const JOB_CATEGORIES = [
  {
    name: "Technology",
    description:
      "Explore jobs building and supporting the digital tools that power modern businesses.",
  },
  {
    name: "Design",
    description:
      "Find creative roles shaping beautiful, intuitive, and engaging experiences.",
  },
  {
    name: "Marketing",
    description:
      "Discover opportunities to grow brands, reach audiences, and drive engagement.",
  },
  {
    name: "Finance",
    description:
      "Explore roles managing money, analysing data, and driving financial growth.",
  },
  {
    name: "Healthcare",
    description:
      "Find rewarding opportunities focused on caring for and improving people's health.",
  },
  {
    name: "Education",
    description:
      "Discover roles helping people learn, grow, and achieve their potential.",
  },
  {
    name: "Sales",
    description:
      "Explore opportunities to connect with customers and drive business revenue.",
  },
  {
    name: "Operations",
    description:
      "Find roles that keep businesses organised, efficient, and running smoothly.",
  },
  {
    name: "Engineering",
    description:
      "Discover opportunities to design, build, and improve innovative solutions.",
  },
  {
    name: "Legal",
    description:
      "Explore careers providing legal advice, support, and professional expertise.",
  },
  {
    name: "Hospitality",
    description:
      "Find roles creating exceptional experiences across hotels, restaurants, and tourism.",
  },
  {
    name: "Domestic & Care",
    description:
      "Discover opportunities providing essential support and care in homes and communities.",
  },
  {
    name: "Office",
    description:
      "Explore administrative and support roles that keep workplaces running efficiently.",
  },
  {
    name: "Events",
    description:
      "Find opportunities planning, coordinating, and delivering memorable experiences.",
  },
  {
    name: "Beauty & Fashion",
    description:
      "Discover creative roles in beauty, style, fashion, and personal care.",
  },
] as const;
  
export const JOB_TYPES = [
  "Full-time", 
  "Part-time", 
  "Contract", 
  "Internship", 
  "Freelance"
] as const

export const EXPERIENCE_LEVELS = [
  "Internship",
  "Junior",
  "Intermediate",
  "Senior",
  "Lead",
  "Director",
] as const;

export const SORT_OPTIONS = [
  "Most Relevant",
  "Most Recent",
  "Highest Salary",
  "Lowest Salary",
] as const;

export const JOB_STATUS = [
  "All",
  'Available', 
  'Unavailable'
] as const

export const TOP_LOCATIONS = [
  "Lagos",
  "Abuja",
  "Enugu",
  "Port Harcourt",
  "Ibadan",
] as const

export const DATE_POSTED = [
  ['Any time', 'any'], 
  ['Last 24 hours', '1'],
  ['Last 3 days', '3'], 
  ['Last week', '7'], 
  ['Last month', '30'],
] as const

export const VIEW_MODE = [
  'List',
  'Grid'
] as const

export const JOBS_PER_PAGE = 9;


export const JOB_LISTINGS: JobListing[] = [
  {
    id: crypto.randomUUID(),
    title: "Waitress",
    category: "Hospitality",
    type: "Part-time",
    level: "Junior",
    city: "Nsukka",
    state: "Enugu",
    area: "Total Roundabout",
    salary: 25000,
    postedAt: "2026-08-17",
    status: "Unavailable",
    featured: true,
    tags: ["Waitress", "Cashier", "Sales Rep"],
  },
  {
    id: crypto.randomUUID(),
    title: "Bar Man/Woman",
    category: "Hospitality",
    type: "Full-time",
    level: "Intermediate",
    city: "Nsukka",
    state: "Enugu",
    area: "Total Roundabout",
    salary: 35000,
    postedAt: "2026-08-16",
    status: "Available",
    featured: true,
    tags: ["Bar Man", "Bar Lady", "Sales Rep"],
  },
  {
    id: crypto.randomUUID(),
    title: "Snooker Attendant",
    category: "Hospitality",
    type: "Part-time",
    level: "Internship",
    city: "Nsukka",
    state: "Enugu",
    area: "Total Roundabout",
    salary: 35000,
    postedAt: "2026-08-15",
    status: "Unavailable",
    featured: true,
    tags: ["Snooker Attendant", "Games", "Hospitality"],
  },
  {
    id: crypto.randomUUID(),
    title: "POS Attendant",
    category: "Sales",
    type: "Full-time",
    level: "Junior",
    city: "Nsukka",
    state: "Enugu",
    area: "Nsukka Town",
    salary: 30000,
    postedAt: "2026-08-14",
    status: "Available",
    featured: false,
    tags: ["POS Attendant", "Cashier", "Sales"],
  },
  {
    id: crypto.randomUUID(),
    title: "Computer Operator",
    category: "Office",
    type: "Contract",
    level: "Intermediate",
    city: "Nsukka",
    state: "Enugu",
    area: "UNN First Gate",
    salary: 30000,
    postedAt: "2026-08-12",
    status: "Unavailable",
    featured: false,
    tags: ["Computer Operator", "Data Entry", "IT Support"],
  },
  {
    id: crypto.randomUUID(),
    title: "Cyber Assistant",
    category: "Office",
    type: "Part-time",
    level: "Junior",
    city: "Nsukka",
    state: "Enugu",
    area: "UNN First Gate",
    salary: 30000,
    postedAt: "2026-08-10",
    status: "Unavailable",
    featured: false,
    tags: ["Cyber Assistant", "Cafe Attendant", "Computer Operator"],
  },
  {
    id: crypto.randomUUID(),
    title: "Basic Computer Tutor",
    category: "Education",
    type: "Freelance",
    level: "Senior",
    city: "Nsukka",
    state: "Enugu",
    area: "UNN First Gate",
    salary: 30000,
    postedAt: "2026-08-08",
    status: "Unavailable",
    featured: false,
    tags: ["Computer Tutor", "Trainer", "Education"],
  },
  {
    id: crypto.randomUUID(),
    title: "Nail Technician",
    category: "Beauty & Fashion",
    type: "Full-time",
    level: "Intermediate",
    city: "Nsukka",
    state: "Enugu",
    area: "UNN Malima",
    salary: 40000,
    postedAt: "2026-08-05",
    status: "Available",
    featured: false,
    tags: ["Nail Technician", "Beautician", "Manicurist"],
  },
  {
    id: crypto.randomUUID(),
    title: "Barber",
    category: "Beauty & Fashion",
    type: "Full-time",
    level: "Senior",
    city: "Nsukka",
    state: "Enugu",
    area: "UNN Malima",
    salary: 45000,
    postedAt: "2026-08-03",
    status: "Available",
    featured: false,
    tags: ["Barber", "Haircut", "Grooming"],
  },
  {
    id: crypto.randomUUID(),
    title: "Shawarma Sales Rep",
    category: "Sales",
    type: "Part-time",
    level: "Junior",
    city: "Nsukka",
    state: "Enugu",
    area: "Orba Road",
    salary: 25000,
    postedAt: "2026-07-29",
    status: "Available",
    featured: false,
    tags: ["Shawarma", "Sales Rep", "Food Vendor"],
  },
  {
    id: crypto.randomUUID(),
    title: "Kitchen Chef",
    category: "Hospitality",
    type: "Full-time",
    level: "Senior",
    city: "Nsukka",
    state: "Enugu",
    area: "UNN Nsukka",
    salary: 40000,
    postedAt: "2026-07-25",
    status: "Available",
    featured: false,
    tags: ["Kitchen Chef", "Cook", "Culinary"],
  },
  {
    id: crypto.randomUUID(),
    title: "Nurse / Primary School Tutor",
    category: "Education",
    type: "Contract",
    level: "Intermediate",
    city: "Nsukka",
    state: "Enugu",
    area: "Fen Park",
    salary: 30000,
    postedAt: "2026-07-20",
    status: "Unavailable",
    featured: false,
    tags: ["Nurse", "School Tutor", "Caregiver"],
  },
  {
    id: crypto.randomUUID(),
    title: "Sales Representative",
    category: "Sales",
    type: "Full-time",
    level: "Junior",
    city: "Nsukka",
    state: "Enugu",
    area: "Opp Shanaha",
    salary: 30000,
    postedAt: "2026-07-18",
    status: "Unavailable",
    featured: false,
    tags: ["Sales Representative", "Retail", "Customer Service"],
  },
  {
    id: crypto.randomUUID(),
    title: "Sales Rep / Cashier",
    category: "Sales",
    type: "Part-time",
    level: "Intermediate",
    city: "Nsukka",
    state: "Enugu",
    area: "Aku Road",
    salary: 40000,
    postedAt: "2026-07-10",
    status: "Available",
    featured: false,
    tags: ["Sales Rep", "Cashier", "Retail"],
  },
  {
    id: crypto.randomUUID(),
    title: "Sales Rep",
    category: "Sales",
    type: "Freelance",
    level: "Junior",
    city: "Nsukka",
    state: "Enugu",
    area: "UNN",
    salary: 30000,
    postedAt: "2026-07-01",
    status: "Available",
    featured: false,
    tags: ["Sales Rep", "Marketing", "Retail"],
  },
  {
    id: crypto.randomUUID(),
    title: "Live-in House Help",
    category: "Domestic & Care",
    type: "Full-time",
    level: "Intermediate",
    city: "Nsukka",
    state: "Enugu",
    area: "Ofulonu",
    salary: 30000,
    postedAt: "2026-06-20",
    status: "Available",
    featured: false,
    tags: ["House Help", "Domestic", "Caregiver"],
  },
  {
    id: crypto.randomUUID(),
    title: "Restaurant Chef",
    category: "Hospitality",
    type: "Full-time",
    level: "Senior",
    city: "Nsukka",
    state: "Enugu",
    area: "Aku Road",
    salary: 30000,
    postedAt: "2026-06-05",
    status: "Available",
    featured: false,
    tags: ["Restaurant Chef", "Cook", "Kitchen"],
  },
  {
    id: crypto.randomUUID(),
    title: "Restaurant Waitress",
    category: "Hospitality",
    type: "Part-time",
    level: "Junior",
    city: "Nsukka",
    state: "Enugu",
    area: "Aku Road",
    salary: 25000,
    postedAt: "2026-05-25",
    status: "Available",
    featured: false,
    tags: ["Waitress", "Server", "Hospitality"],
  },
  {
    id: crypto.randomUUID(),
    title: "Primary School Maths Teacher",
    category: "Education",
    type: "Full-time",
    level: "Senior",
    city: "Nsukka",
    state: "Enugu",
    area: "Onuiyi",
    salary: 40000,
    postedAt: "2026-05-10",
    status: "Available",
    featured: false,
    tags: ["Maths Teacher", "Primary School", "Tutor"],
  },
  {
    id: crypto.randomUUID(),
    title: "Hotel Receptionist",
    category: "Hospitality",
    type: "Full-time",
    level: "Intermediate",
    city: "Nsukka",
    state: "Enugu",
    area: "Orba Road",
    salary: 45000,
    postedAt: "2026-04-25",
    status: "Unavailable",
    featured: false,
    tags: ["Receptionist", "Front Desk", "Hospitality"],
  },
  {
    id: crypto.randomUUID(),
    title: "Hotel Waitress",
    category: "Hospitality",
    type: "Part-time",
    level: "Junior",
    city: "Nsukka",
    state: "Enugu",
    area: "Orba Road",
    salary: 45000,
    postedAt: "2026-04-10",
    status: "Unavailable",
    featured: false,
    tags: ["Hotel Waitress", "Server", "Hospitality"],
  },
  {
    id: crypto.randomUUID(),
    title: "Office Assistant",
    category: "Office",
    type: "Contract",
    level: "Intermediate",
    city: "Nsukka",
    state: "Enugu",
    area: "Total Roundabout",
    salary: 40000,
    postedAt: "2026-03-25",
    status: "Unavailable",
    featured: false,
    tags: ["Office Assistant", "Admin", "Clerical"],
  },
  {
    id: crypto.randomUUID(),
    title: "Live-in House Help",
    category: "Domestic & Care",
    type: "Full-time",
    level: "Junior",
    city: "Nsukka",
    state: "Enugu",
    area: "Nru",
    salary: 40000,
    postedAt: "2026-03-10",
    status: "Available",
    featured: false,
    tags: ["House Help", "Domestic", "Live-in"],
  },
  {
    id: crypto.randomUUID(),
    title: "Sales Rep",
    category: "Sales",
    type: "Freelance",
    level: "Intermediate",
    city: "Nsukka",
    state: "Enugu",
    area: "UNN",
    salary: 40000,
    postedAt: "2026-02-25",
    status: "Available",
    featured: false,
    tags: ["Sales Rep", "Retail", "Customer Service"],
  },
  {
    id: crypto.randomUUID(),
    title: "Live-in Security",
    category: "Sales",
    type: "Full-time",
    level: "Lead",
    city: "Nsukka",
    state: "Enugu",
    area: "Ugwuoye",
    salary: 60000,
    postedAt: "2026-02-10",
    status: "Available",
    featured: false,
    tags: ["Security", "Guard", "Live-in"],
  },
  {
    id: crypto.randomUUID(),
    title: "Kitchen Chef",
    category: "Hospitality",
    type: "Contract",
    level: "Senior",
    city: "Nsukka",
    state: "Enugu",
    area: "Nsukka",
    salary: 60000,
    postedAt: "2026-01-25",
    status: "Available",
    featured: false,
    tags: ["Kitchen Chef", "Cook", "Culinary"],
  },
  {
    id: crypto.randomUUID(),
    title: "Cashier",
    category: "Hospitality",
    type: "Part-time",
    level: "Junior",
    city: "Nsukka",
    state: "Enugu",
    area: "Nsukka",
    salary: 55000,
    postedAt: "2026-01-10",
    status: "Unavailable",
    featured: false,
    tags: ["Cashier", "POS", "Sales"],
  },
  {
    id: crypto.randomUUID(),
    title: "Supervisor",
    category: "Hospitality",
    type: "Full-time",
    level: "Lead",
    city: "Nsukka",
    state: "Enugu",
    area: "Nsukka",
    salary: 75000,
    postedAt: "2025-12-20",
    status: "Available",
    featured: true,
    tags: ["Supervisor", "Manager", "Operations"],
  },
];